$path = 'c:\Users\ttrob\.gemini\antigravity\scratch\components\TeachersModule.tsx'
$c = Get-Content $path
# Find the line with </div > (the main container end)
$foundIndex = -1
for ($i = $c.Count - 1; $i -ge 0; $i--) {
    if ($c[$i].Trim() -eq '</div >') {
        $foundIndex = $i
        break
    }
}

if ($foundIndex -ne -1) {
    # Replace from that line to the end
    $newContent = $c[0..($foundIndex-1)]
    $newContent += '         {/* AI QUESTION TAGGING MODAL */}'
    $newContent += '         {'
    $newContent += '            isQuestionTaggingModalOpen && taggingExam && ('
    $newContent += '               <div className="fixed inset-0 z-[9000] flex items-center justify-center bg-black/95 backdrop-blur-md px-4">'
    $newContent += '                  <div className="bg-[#0d141b] border-2 border-[#3b82f6] w-full max-w-2xl h-[80vh] flex flex-col shadow-2xl animate-in zoom-in-95 duration-200 rounded-sm">'
    $newContent += '                     <div className="p-5 border-b border-white/10 flex justify-between items-center bg-[#162431] shrink-0">'
    $newContent += '                        <div className="flex items-center gap-4">'
    $newContent += '                           <div className="w-12 h-12 bg-[#3b82f6]/10 border border-[#3b82f6] flex items-center justify-center rounded-sm">'
    $newContent += '                              <i className="fa-solid fa-wand-magic-sparkles text-[#3b82f6] text-xl"></i>'
    $newContent += '                           </div>'
    $newContent += '                           <div>'
    $newContent += '                              <h3 className="text-[14px] font-black text-white uppercase tracking-widest">AI AKADEMİK ANALİZÖR</h3>'
    $newContent += '                              <span className="text-[8px] font-bold text-slate-400 uppercase tracking-[0.3em] mt-1 block">{taggingExam.lessonName} | {taggingExam.className}</span>'
    $newContent += '                           </div>'
    $newContent += '                        </div>'
    $newContent += '                        <button onClick={() => setIsQuestionTaggingModalOpen(false)} className="w-10 h-10 border border-white/10 text-white/40 hover:text-white transition-all"><i className="fa-solid fa-xmark text-lg"></i></button>'
    $newContent += '                     </div>'
    $newContent += ''
    $newContent += '                     <div className="flex-1 overflow-y-auto custom-scrollbar p-6 bg-grid-hatched">'
    $newContent += '                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">'
    $newContent += '                           {/* LEFT: UPLOAD & PARAMS */}'
    $newContent += '                           <div className="space-y-6">'
    $newContent += '                              <div className="p-6 bg-black/40 border border-white/5 rounded-sm flex flex-col items-center justify-center text-center group cursor-pointer hover:border-[#3b82f6]/50 transition-all">'
    $newContent += '                                 <i className="fa-solid fa-file-pdf text-4xl text-slate-600 mb-4 group-hover:text-[#3b82f6] transition-all"></i>'
    $newContent += '                                 <h4 className="text-[11px] font-black text-white uppercase mb-1">SINAV DOSYASINI YÜKLE</h4>'
    $newContent += '                                 <p className="text-[8px] font-bold text-slate-500 uppercase">PDF veya JPEG (SORU KİTAPÇIĞI)</p>'
    $newContent += '                                 <div className="mt-6 w-full h-1 bg-white/5 relative overflow-hidden">'
    $newContent += '                                    <div className="absolute inset-0 bg-[#3b82f6] w-0"></div>'
    $newContent += '                                 </div>'
    $newContent += '                              </div>'
    $newContent += ''
    $newContent += '                              <div className="space-y-4">'
    $newContent += '                                 <div className="flex justify-between items-center">'
    $newContent += '                                    <span className="text-[9px] font-black text-slate-400 uppercase">ANALİZ DERİNLİĞİ</span>'
    $newContent += '                                    <span className="text-[10px] font-black text-[#3b82f6]">PROFESYONEL</span>'
    $newContent += '                                 </div>'
    $newContent += '                                 <div className="grid grid-cols-2 gap-2">'
    $newContent += '                                    <button className="h-10 border border-[#3b82f6] bg-[#3b82f6]/10 text-[#3b82f6] font-black text-[9px] uppercase">GELİŞMİŞ EŞLEŞTİRME</button>'
    $newContent += '                                    <button className="h-10 border border-white/5 bg-black/20 text-slate-600 font-black text-[9px] uppercase hover:text-white transition-all">HIZLI TARAMA</button>'
    $newContent += '                                 </div>'
    $newContent += '                              </div>'
    $newContent += '                           </div>'
    $newContent += ''
    $newContent += '                           {/* RIGHT: AI LOGS */}'
    $newContent += '                           <div className="bg-black/60 border border-white/5 p-4 font-mono flex flex-col h-[400px]">'
    $newContent += '                              <div className="flex items-center gap-2 mb-4 shrink-0">'
    $newContent += '                                 <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>'
    $newContent += '                                 <span className="text-[9px] font-black text-slate-500 uppercase">AI_ENGINE_LOGS</span>'
    $newContent += '                              </div>'
    $newContent += '                              <div className="flex-1 overflow-y-auto no-scrollbar space-y-1">'
    $newContent += '                                 {isTaggingActive ? ('
    $newContent += '                                    <>'
    $newContent += '                                       <p className="text-[10px] text-green-500/80 uppercase">{\">\">\"} DOSYA OKUNUYOR: {taggingExam.lessonName}_KITAPCIK.PDF</p>'
    $newContent += '                                       <p className="text-[10px] text-blue-400 uppercase">{\">\">\"} OCR MOTORU BAŞLATILDI...</p>'
    $newContent += '                                       <p className="text-[10px] text-white/60 uppercase">{\">\">\"} 24 SORU TESPİT EDİLDİ.</p>'
    $newContent += '                                       <p className="text-[10px] text-orange-400 uppercase">{\">\">\"} GEMINI-1.5-PRO BAĞLANTISI KURULDU.</p>'
    $newContent += '                                       <p className="text-[10px] text-white/40 uppercase">{\">\">\"} KAZANIM EŞLEŞTİRME BAŞLATILIYOR...</p>'
    $newContent += '                                    </>'
    $newContent += '                                 ) : ('
    $newContent += '                                    <p className="text-[10px] text-slate-700 uppercase italic">ANALİZ BAŞLATILMADI...</p>'
    $newContent += '                                 )}'
    $newContent += '                              </div>'
    $newContent += '                           </div>'
    $newContent += '                        </div>'
    $newContent += '                     </div>'
    $newContent += ''
    $newContent += '                     <div className="p-4 bg-[#162431] border-t border-white/10 shrink-0">'
    $newContent += '                        <button'
    $newContent += '                           onClick={() => setIsTaggingActive(true)}'
    $newContent += '                           disabled={isTaggingActive}'
    $newContent += '                           className="w-full h-14 bg-[#3b82f6] text-white font-black text-[13px] uppercase tracking-[0.4em] shadow-xl hover:brightness-110 active:scale-[0.98] transition-all border border-white/10 disabled:opacity-50"'
    $newContent += '                        >'
    $newContent += '                           {isTaggingActive ? \"ANALİZ YAPILIYOR...\" : \"AI ANALİZİ BAŞLAT\"}'
    $newContent += '                        </button>'
    $newContent += '                     </div>'
    $newContent += '                  </div>'
    $newContent += '               </div>'
    $newContent += '            )'
    $newContent += '         }'
    $newContent += '      </div >'
    $newContent += '   );'
    $newContent += '};'
    $newContent += ''
    $newContent += 'export default TeachersModule;'
    
    $newContent | Set-Content $path
}
